surf-spots-fe:
  component: "@sls-next/serverless-component@1.18"
  inputs:
    description: "Surf Spot NextJS app front end deployed on Lambda@Edge"
    name:
      defaultLambda: nextjs-surf-spot-fe-app-default
      apiLambda: nextjs-surf-spot-fe-app-api
    AccelerateConfiguration:
      AccelerationStatus: Enabled
    build:
      env:

